Add enable cast option
bricolages/queuery_client pull request #7
Opened 2021-08-30 11:20 UTC by ragi256

RedshiftのUnloadで使えるMANIFESTオプションを有効にできるようにします
https://docs.aws.amazon.com/ja_jp/redshift/latest/dg/r_UNLOAD.html

有効にすると出力された `result.csv.manifest` ファイルにある型定義をもとに結果を自動で型変換します。
valuesを省力しても動きます。互換性を考えて無指定の場合は従来通り動きます。

```ruby
bundle = QueueryClient.query('select 0, 1.23, 'hoge', current_date')
bundle.each.to_a
# => [['0', '1.23', '2021-08-30 00:00:00']]

bundle = QueueryClient.query('select 0, 1.23, 'hoge', current_date', enable_cast: true)
bundle.each.to_a
# => [[0, 1.23,  #<Date: 2021-08-30 ((2459457j,0s,0n),+0s,2299161j)>]]
```

2021-08-31 01:51 UTC, aamine requested changes
column_typesのキャッシュは必須にて

2021-08-31 01:51 UTC, aamine commented on lib/queuery_client/client.rb
> +    def execute_query(select_stmt, values, enable_cast)
このメソッドもキーワード引数でよくない？

2021-08-31 01:51 UTC, aamine commented on lib/queuery_client/client.rb
> +    def query_and_wait(select_stmt, values, enable_cast)
このメソッドもキーワード引数でよくない？

2021-08-31 01:51 UTC, aamine commented on lib/queuery_client/client.rb
> +    def query(select_stmt, values, enable_cast)
このメソッドもキーワード引数でよくない？ (3)

2021-08-31 01:51 UTC, aamine commented on lib/queuery_client/data_file_bundle.rb
> +          value
サポートしてない型は例外にすべきでは。
あとからキャストするように変えるのはきついと思う。

2021-08-31 01:51 UTC, aamine commented on lib/queuery_client/manifest_file.rb
> +    end
[MUST] このメソッドの結果は絶対にキャッシュすべき。このメソッド、行ごとに呼んでるよね？ つまりこれ行ごとにS3アクセスしてない？

2021-08-31 01:51 UTC, aamine commented on lib/queuery_client/manifest_file.rb
> +  class ManifestFile
コンストラクタがない？！ってあせったのでコメントでabstract classであるむねを書いておいてほしい

2021-08-31 09:46 UTC, ragi256 commented on lib/queuery_client/manifest_file.rb
> +  class ManifestFile
見やすいコメント形式がわからなかったのでとりあえずクラス名の横につけておきました（上に書くべき？）
https://github.com/bricolages/queuery_client/pull/7/commits/88703eebe50d2105f49e0c37042f5781c7aff0b7

2021-08-31 09:46 UTC, ragi256 commented on lib/queuery_client/manifest_file.rb
> +    end
1クエリにつきS3アクセス1回のつもりだったのですが、このままだと毎回openしてアクセスしてるのでインスタンス変数にキャッシュしました　https://github.com/bricolages/queuery_client/pull/7/commits/ee063209a45623d0591872657de7ebf228ed674c

2021-08-31 09:46 UTC, ragi256 commented on lib/queuery_client/client.rb
> +    def query(select_stmt, values, enable_cast)
✅  https://github.com/bricolages/queuery_client/pull/7/commits/8e5b1cbc5d7bf504f79915984dc39a5e6881972e

2021-08-31 09:46 UTC, ragi256 commented on lib/queuery_client/client.rb
> +    def query_and_wait(select_stmt, values, enable_cast)
✅  https://github.com/bricolages/queuery_client/pull/7/commits/8e5b1cbc5d7bf504f79915984dc39a5e6881972e

2021-08-31 09:46 UTC, ragi256 commented on lib/queuery_client/client.rb
> +    def execute_query(select_stmt, values, enable_cast)
確かに……
✅  https://github.com/bricolages/queuery_client/pull/7/commits/8e5b1cbc5d7bf504f79915984dc39a5e6881972e

2021-08-31 09:49 UTC, ragi256 commented on lib/queuery_client/data_file_bundle.rb
> +          value
確かに中途半端にキャスト済と未キャストが混ざったrowを返すよりまるっと1行キャスト可能化不可能かで判断したほうが良さそうですね。無理だったら従来どおり文字列を受け取って自前でなんとかすればいいので。例外出します。
https://github.com/bricolages/queuery_client/pull/7/commits/15cf9c709d734f150d0bb8a99f17d8f1f679f15d

2021-08-31 11:02 UTC, aamine approved these changes

2021-08-31 11:02 UTC, aamine commented on lib/queuery_client/data_file_bundle.rb
> +    def type_cast(row)
nits: private

2021-10-07 06:02 UTC, ragi256 commented
https://github.com/bricolages/redshift_connector/pull/21#discussion_r722832642 より
RedshiftConnectorのほうとの兼ね合いもあり、型をキャストするコードは単一モジュールとしてファイルに吐き出しました。 770f7b1

2021-10-07 06:03 UTC, merged